#!/usr/bin/env node

var fs = require('fs')
var path = require('path')
var cp = require('child_process')

var nopt = require('nopt')
var Promise = require('bluebird')

Promise.promisifyAll(fs)

var options = nopt({
  'input': Array,
  'all': Boolean
}, {
  'i': ['--input'],
  'a': ['--all', 'true']
}, process.argv, 2)

var main = path.join(process.cwd(), 'build')

if (options.all) {
  fs.readdirAsync(main)
    .filter(function (dir) {
      return fs.statAsync(path.join(main, dir))
        .then(function (stat) {
          return stat.isDirectory()
        })
    })
    .then(function (dirs) {
      return dirs.map(function (dir) {
        return {
          name: dir,
          input: path.join(main, dir, 'src'),
          output: path.join(main, dir, 'build'),
        }
      })
    })
    .map(function (info) {
      var command = ['babel'].concat([info.input, '-d', info.output]).join(' ')

      cp.exec(command, {cwd: path.join(process.cwd())}, function (error, stdout, stderr) {
        if (error) {
          console.error('exec error:' + error)
        } else {
          if (stdout) {
            console.log('Finish：' + stdout)

            var command = ['grunt', 'copy'].join(' ')
            cp.exec(command, {cwd: path.join(process.cwd())}, function (error, stdout, stderr) {
              if (error) {
                console.error('exec error:' + error)
              } else {
                stdout && console.log('Finish：' + stdout)
                stderr && console.error(stderr)
              }
            })
          } else if (stderr) {
            stderr && console.error(stderr)
          }
        }
      })
    })
}
else {
  if (options.input.length) {
    for (var i = 0; i < options.input.length; i++) {
      var command = ['babel', 'src', '-d', 'build'].join(' ')
      var dir = options.input[i]

      cp.exec(command, {cwd: path.join(process.cwd(), dir)}, function (error, stdout, stderr) {
        if (error) {
          console.error('exec error:' + error)
        } else {
          stdout && console.log('Finish：' + stdout)
          stderr && console.error(stderr)
        }
      })
    }
  }
  else {
    console.error('need input less file')
  }
}